version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - PORT=5000
    # Required for Playwright/Selenium to work properly
    shm_size: '2gb'
    restart: unless-stopped