services:
  - type: web
    name: facebook-ad-scraper
    env: docker
    region: oregon  # Choose a region closest to your users
    plan: starter    # Adjust based on your needs (free, starter, etc.)
    
    # Build and deployment settings
    dockerfilePath: ./Dockerfile
    dockerCommand: Xvfb :99 -screen 0 1280x1024x24 -ac &> /dev/null & gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 app:app
    
    # Autoscaling and resource settings (adjust as needed)
    autoDeploy: true
    numInstances: 1
    
    # Health check
    healthCheckPath: /health
    healthCheckTimeout: 30s
    
    # Environment variables
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DISPLAY
        value: :99
    
    # Disk settings - for file storage
    disk:
      name: downloads
      mountPath: /app/downloads
      sizeGB: 5